/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as FormateurRouteImport } from './routes/formateur'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as CoursRouteImport } from './routes/cours'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const FormateurRoute = FormateurRouteImport.update({
  id: '/formateur',
  path: '/formateur',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursRoute = CoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/flashcards': typeof FlashcardsRoute
  '/formateur': typeof FormateurRoute
  '/glossaire': typeof GlossaireRoute
  '/modules': typeof ModulesRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/flashcards': typeof FlashcardsRoute
  '/formateur': typeof FormateurRoute
  '/glossaire': typeof GlossaireRoute
  '/modules': typeof ModulesRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/flashcards': typeof FlashcardsRoute
  '/formateur': typeof FormateurRoute
  '/glossaire': typeof GlossaireRoute
  '/modules': typeof ModulesRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cours'
    | '/flashcards'
    | '/formateur'
    | '/glossaire'
    | '/modules'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cours'
    | '/flashcards'
    | '/formateur'
    | '/glossaire'
    | '/modules'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/cours'
    | '/flashcards'
    | '/formateur'
    | '/glossaire'
    | '/modules'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursRoute: typeof CoursRoute
  FlashcardsRoute: typeof FlashcardsRoute
  FormateurRoute: typeof FormateurRoute
  GlossaireRoute: typeof GlossaireRoute
  ModulesRoute: typeof ModulesRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formateur': {
      id: '/formateur'
      path: '/formateur'
      fullPath: '/formateur'
      preLoaderRoute: typeof FormateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours': {
      id: '/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof CoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursRoute: CoursRoute,
  FlashcardsRoute: FlashcardsRoute,
  FormateurRoute: FormateurRoute,
  GlossaireRoute: GlossaireRoute,
  ModulesRoute: ModulesRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
